export const FETCH_CURRENCY_INIT = 'FETCH_CURRENCY_INIT';
export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
export const FETCH_CURRENCY_FAIL = 'FETCH_CURRENCY_FAIL';

export const SWAP_CURRENCY = 'SWAP_CURRENCY';
